apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-web
  labels:
    app: static-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
        - name: static-web
          image: tienuv1/clinic-website-template:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
